config/routes.rb
Rails.application.routes.draw do

  
  root "pages#home"
  
  resources :pages
  resources :home
  
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "portfolio", to: "pages#portfolio"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        
    end
    
    def about
        
    end
    
    def portfolio
        
    end
    
    def contact
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_background.html.erb
<nav>
    <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
    </ul>
</nav>

<link href='https://fonts.googleapis.com/css?family=Exo:400,900' rel='stylesheet' type='text/css'>
<div class="wrapper">
    <div class="message">
        <h1>Tom Still<br>Developer</h1>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortfolioEmptyherring</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<%= render "layouts/background" %>

app/views/pages/contact.html.erb
<%= render "layouts/background" %>

app/views/pages/home.html.erb
<link href='https://fonts.googleapis.com/css?family=Exo:400,900' rel='stylesheet' type='text/css'>
<div class="wrapper">
  <div class="message">
    <h1>Tom Still</h1>    
  </div>
</div>

app/views/pages/portfolio.html.erb
<%= render "layouts/background" %>